image_width: 2048
image_height: 1536
camera_name: CNS-CWC6:U79085000764
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1828.51242,     0.     ,  1113.88331,
             0.     ,  1825.66507,   732.67529,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.425269, 0.158098, 0.001967, 0.000233, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1531.01355,     0.     ,  1151.53624,     0.     ,
             0.     ,  1671.31726,   727.97551,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
