#==============#
# Camera Model #
#==============#

Camera.name: "stereo0/left"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 1208.1284007496413
Camera.fy: 1206.5856957023066
Camera.cx: 630.3547894350759
Camera.cy: 331.6259218285277

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0


Camera.fps: 30.0
Camera.cols: 1280
Camera.rows: 720

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 1000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer.keyframe_size: 0.06
PangolinViewer.keyframe_line_width: 1
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.07
PangolinViewer.camera_line_width: 2
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -20
PangolinViewer.viewpoint_z: -0.1
PangolinViewer.viewpoint_f: 2800
