TrajectoryPlannerROS:

  # Current limits based on AZ3 standalone configuration.
  acc_lim_x:  0.75
  acc_lim_y:  0.75
  acc_lim_theta: 0.5
  max_vel_x:  0.6
  min_vel_x:  0.15
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.1
  escape_vel: -0.10
  holonomic_robot: true

  xy_goal_tolerance:  0.20
  yaw_goal_tolerance: 0.20

  sim_time: 3
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40

  goal_distance_bias: 32.0
  path_distance_bias: 20.0
  occdist_scale: 0.02
  heading_lookahead: 0.325
  dwa: true

  oscillation_reset_dist: 0.05
  meter_scoring: true
