obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.38, 0.38], [0.38, -0.38], [-0.38, -0.38], [-0.38, 0.38]]
#robot_radius: ir_of_robot
inflation_radius: 0.3
max_obstacle_height: 0.6

# laser_scan_sensor

# laser_scan_sensor: {sensor_frame: os1_sensor, data_type: LaserScan, topic: /porter/os1_cloud_node/scan, marking: true, clearing: true}

NavfnROS:
    allow_unknown: true

recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear: 
    reset_distance: 3.00
aggressive_clear:
    reset_distance: 1.84
