<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="porter">  
  <!-- Camera -->
	<link name="camera_main">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${camera_box_size} ${camera_box_size} ${camera_box_size}"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${camera_box_size} ${camera_box_size} ${camera_box_size}"/>
			</geometry>
			<material name="red"/>
		</visual>

		<inertial>
			<mass value="1e-5" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>
	
	<joint name="camera_joint" type="fixed">
		<axis xyz="0 0 0" />
		<origin xyz="${camera_posx} ${camera_posy} ${support_height/2 + camera_box_size/2 + camera_posz}" rpy="0 0 0"/>
		<parent link="support"/>
		<child link="camera_main"/>
	</joint>

 	
	<gazebo reference="camera_main">
	<sensor type="camera" name="camera_main">
		<update_rate>60.0</update_rate>
		<camera name="head">
		<horizontal_fov>1.3962634</horizontal_fov>
		<image>
			<width>640</width>
			<height>480</height>
			<format>R8G8B8</format>
		</image>
		<clip>
			<near>0.02</near>
			<far>300</far>
		</clip>
		<noise>
			<type>gaussian</type>
			<!-- Noise is sampled independently per pixel on each frame.
			That pixel's noise value is added to each of its color
			channels, which at that point lie in the range [0,1]. -->
			<mean>0.0</mean>
			<stddev>0.007</stddev>
		</noise>
		</camera>
		<plugin name="camera_controller" filename="libgazebo_ros_camera.so">
		<alwaysOn>true</alwaysOn>
		<updateRate>0.0</updateRate>
		<cameraName>/camera_main</cameraName>
		<imageTopicName>image_raw</imageTopicName>
		<cameraInfoTopicName>camera_info</cameraInfoTopicName>
		<frameName>camera_main</frameName>
		<hackBaseline>0.07</hackBaseline>
		<distortionK1>0.0</distortionK1>
		<distortionK2>0.0</distortionK2>
		<distortionK3>0.0</distortionK3>
		<distortionT1>0.0</distortionT1>
		<distortionT2>0.0</distortionT2>
		</plugin>
	</sensor>
	</gazebo>
</robot>
