obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.38, 0.38], [0.38, -0.38], [-0.38, -0.38], [-0.38, 0.38]]
#robot_radius: ir_of_robot
inflation_radius: 0.3
max_obstacle_height: 0.6

observation_sources: point_cloud_sensor 
# laser_scan_sensor

# laser_scan_sensor: {sensor_frame: os1_sensor, data_type: LaserScan, topic: /porter/os1_cloud_node/scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: os1_sensor, data_type: PointCloud2, topic: /porter/os1_cloud_node/points, marking: true, clearing: true}
